# Generated by Django 3.2.5 on 2021-07-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('priority', models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=0)),
                ('due_date', models.DateField(default='2021-07-27')),
                ('due_time', models.TimeField(default='11:16')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.ForeignKey(default='Tasks', on_delete=django.db.models.deletion.PROTECT, to='ToDo.category')),
            ],
        ),
    ]
